### ISSUE TITLE
define vs require

### ISSUE THREAD

**Issue by pwmckenna** [domenic/grunt-amd-wrap#1]
not sure if this discussion belongs here or in amd-wrap, but it would be nice to expose the ability to wrap modules in a require rather than a define behind a grunt config option.

**Comment by domenic** [comment]
You can't wrap modules in a require; that's not AMD syntax.

**Comment by pwmckenna** [comment]
er, true. i guess i'm getting lost trying to convert my main file, which won't load if its defined as a module. the file is `require([], function () { startApp(); });`...I want the nice commonjs non-indented syntax..perhaps this is just not possible for any file that i'm going to load from html?

**Comment by domenic** [comment]
Yeah, it is traditional for AMD code to have one entry file that is basically

``` js
requirejs(["js/main"], function (main) {
  main.start();
});
```

whether that's inlined in a `<script>` tag or used as the entry file when creating the optimized bundle.

**Comment by pwmckenna** [comment]
that little extra of abstraction is what i was missing. thanks!
